### ISSUE TITLE
How to run cdk inside lambda function

### ISSUE THREAD

**Issue by vumdao** [alexpulver/aws-cdk-sam-chalice#2]

**Comment by alexpulver** [comment]
Hi @vumdao,

You can install AWS CDK tooling in an AWS Lambda [layer](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html), and then use the function handler to invoke the `cdk` commands. There is an example from community for this approach: [Running AWS CDK from a Lambda function](https://dev.to/mraszplewicz/running-aws-cdk-from-a-lambda-function-3502).

With recently announced [Container Image Support](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/) for Lambda, you can create your own image instead of Lambda layer.
